#!/bin/sh

"$AMSBIN/ams" << eor

Task GeometryOptimization
GeometryOptimization
    OptimizeLattice Yes
End
System
    Atoms
        P       0.000000000    -0.424426038     1.057626020
        P      -0.000000000     0.424426038    -1.057626020
        P       1.649081135     1.919170121    -1.057626020
        P      -1.649081135    -1.919170121     1.057626020
    End
    Lattice
                3.298162271    -0.000000000     0.000000000
               -0.000000000     4.687192318     0.000000000
    End
End

Engine BAND
    Basis
        Type TZP
        Core None
    End
    BandStructure
        Enabled Yes
        DeltaK 0.01
    End
    EffectiveMass
        Enabled Yes
    End
    KSpace
        Type Symmetric
        Quality Good
    End
    NumericalQuality Good
    XC
        libxc pbe
    End
EndEngine
eor